name: Push Images to ECR

on:
  push:
    branches: [ main ]

jobs:
  push_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to AWS ECR
        uses: aws-actions/aws-ecr-login@v2
        with:
          aws-region: ca-central-1
          registry: 058264132523.dkr.ecr.ca-central-1.amazonaws.com

      - name: List Docker images
        run: |
          echo "Images to push:"
          for image in "${{ env.IMAGES[@] }}"; do
            echo "  - $image"
          done

      - name: Set up Docker cache
        uses: actions/cache@v3
        with:
          path: ~/.docker/dch
          key: ${{ runner.os }}-docker-${{ hashFiles('Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Install Docker CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Build and push images to ECR
        run: |
          for image in "${{ env.IMAGES[@] }}"; do
            echo "Pushing Docker image: $image"
            trimmed_image="${image##*/}"
            tagged_image="$ECR_REPOSITORY:${trimmed_image}"
            docker build -t "$image" .
            docker tag "$image" "$tagged_image"
            docker push "$tagged_image"
          done

env:
  IMAGES: |
    gcr.io/google-samples/microservices-demo/emailservice:v0.9.0
    gcr.io/google-samples/microservices-demo/checkoutservice:v0.9.0
    gcr.io/google-samples/microservices-demo/recommendationservice:v0.9.0
    gcr.io/google-samples/microservices-demo/frontend:v0.9.0
    gcr.io/google-samples/microservices-demo/paymentservice:v0.9.0
    gcr.io/google-samples/microservices-demo/productcatalogservice:v0.9.0
    gcr.io/google-samples/microservices-demo/cartservice:v0.9.0
    gcr.io/google-samples/microservices-demo/loadgenerator:v0.9.0
    gcr.io/google-samples/microservices-demo/currencyservice:v0.9.0
    gcr.io/google-samples/microservices-demo/shippingservice:v0.9.0
    gcr.io/google-samples/microservices-demo/adservice:v0.9.0
  ECR_REPOSITORY: 058264132523.dkr.ecr.ca-central-1.amazonaws.com/online-boutique